### ISSUE TITLE
How could I import angular2-infinite-scroll bundle using SystemJS module loader?

### ISSUE THREAD

**Issue by bernardopacheco** [orizens/angular2-infinite-scroll#20]
I'm trying to load the angular2-infinite-scroll using SystemJS with this config:

SystemJS configuration:

```
var config = {
  map: { 'angular2-infinite-scroll':   'node_modules/angular2-infinite-scroll/bundles' },
  packages: { 'angular2-infinite-scroll': { main: 'angular2-infinite-scroll.js', defaultExtension: 'js', format: 'register' } }
  };

System.config(config);
```

And in my component the module is loaded:

`import { InfiniteScroll } from 'angular2-infinite-scroll';`

However, the imported InfiniteScroll is empty when I execute my app.

What do I missing?

Thanks

**Comment by orizens** [comment]
Hi @bernardopacheco 
I havn't tried using System.config only. 
There was a discussion on using it in angular-cli. 
look at this thread and see if it helps: https://github.com/orizens/angular2-infinite-scroll/issues/3
otherwise - try to add the name of the js file in the config.map. 
let me know if that works.

**Comment by orizens** [comment]
@bernardopacheco 
can i close this issue?

**Comment by bernardopacheco** [comment]
Absolutely!

**Comment by orizens** [comment]
thanks. 
I added #3 system configuration help in the [wiki](https://github.com/orizens/angular2-infinite-scroll/wiki)
