### ISSUE TITLE
NPM release 0.1.91 broken

### ISSUE THREAD

**Issue by zoehneto** [orizens/angular2-infinite-scroll#65]
The 0.1.91 package in npm doesn't include the `angular2-infinite-scroll.js` and `angular2-infinite-scroll.d.ts` files thereby braking imports in existing applications. These files are still included in the git repo (the typescript source).

**Comment by orizens** [comment]
@zoehneto thanks for reporting.

**Comment by orizens** [comment]
for future reference: 
currently, 6ec6fbf6744f6f541d659d3d2241f9bbfd661191 fixed the bug, and the current version is 0.1.92. 
i run ```npm run prepublish``` twice which produced a new file in the bundles directory. then, i run ```npm publish```. 
@ocombe have you dealt with such an issue before - where the npm prepublish script results in an error? 

Thanks.

**Comment by orizens** [comment]
@zoehneto i think i have found the cause for failed version on npm. 
the prepublish script was using ```tsc & node make.js``` - this runs both commands in parallel - since the make.js needs to be run only after tsc hsa produced the resulted files. 
so - after experimenting with few versions (now 0.1.95) - i added a preversion, version and postversion scripts as explained [here](https://docs.npmjs.com/cli/version) and tested it with the [demo plunker](https://plnkr.co/edit/DzKAiAxtAleIrT0tsqtj?p=preview)
